<?php

/**
 * @file
 *   conductor.module provides a workflow editor with a GUI (or it will).
 */

/**
 * Implement hook_menu().
 */
function conductor_menu() {
  $items = array();
  $items['conductor/ajax'] = array(
    'title' => 'Conductor',
    'page callback' => 'conductor_ajax',
    'theme callback' => 'ajax_base_page_theme',
    'delivery callback' => 'ajax_deliver',
    'access callback' => TRUE,
    'description' => 'Ajax callback for workflow loading.',
    'type' => MENU_CALLBACK,
    'file' => 'includes/ajax.inc',
  );
  return $items;
}
 
/*
 * Implement hook_permission().
 */
function conductor_permission() {
  return array(
    'administer conductor workflows' => array(
      'title' => t('Administer workflows'),
      'description' => t('Access the conductor workflow administration pages.'),
    ),
  );
}

/**
 * Menu callback to load a workflow via AJAX.
 */
function conductor_ajax() {
  if (isset($_REQUEST['conductor_name'])) {
  }
}
