<?php

/**
 * @file conductor_ui.module
 *   Provides the admin interface for Conductor.
 */

/**
 * Implements hook_menu().
 */
function conductor_ui_menu() {
  $items = array();
  $items['admin/structure/conductor'] = array(
    'title' => 'Conductor Workflows',
    'description' => 'Manage custom workflows',
    'page callback' => 'conductor_ui_list',
    'access arguments' => array('administer conductor workflows'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/structure/conductor/list'] = array(
    'title' => 'List Conductor Workflows',
    'page callback' => 'conductor_ui_list',
    'access arguments' => array('administer conductor workflows'),
    'type' => MENU_DEFAULT_LOCAL_TASK,

  );
  $items['admin/structure/conductor/add'] = array(
    'title' => 'Add A New Workflow',
    'page callback' => 'conductor_ui_add_workflow_callback',
    'access arguments' => array('administer conductor workflows'),
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

/**
 * Implements hook_theme();
 */
function conductor_ui_theme() {
  return array(
    'conductor_activity' => array(
      'variables' => array(
        'name' => '',
        'class' => '',
      ),
      'path' => drupal_get_path('module', 'conductor_ui') . '/theme',
      'template' => 'conductor-activity'
    ),
  );
}

/**
 * Implements hook_conductor_activity_process
 * TODO: Test this!
 */
function conductor_ui_conductor_activity_process(&$plugin) {
  $plugin += array(
    'conductor-ui-template' => 'conductor_activity',
  );
}

/**
 * Page callback to list all workflows.
 */
function conductor_ui_list() {
  return '';
}

/**
 * Page callback to add a new workflow.
 */
function conductor_ui_add_workflow_callback() {

  drupal_set_title(t('Add a new Conductor workflow'));
  conductor_ui_add_js();
  conductor_ui_add_css();

  $output = array();
  $output['workflow_element_panel'] = array(
    '#prefix' => '<div id="conductor-ui-toolbar">',
    '#suffix' => '</div>',
  );
  $output['workflow_element_panel']['add_activity'] = array(
    '#type' => 'markup',
    '#markup' => t('Add an activity'),
  );
  $output['workflow_element_panel']['buttons'] = array(
    '#prefix' => '<div id="toolbar-buttons">',
    '#suffix' => '</div>',
  );
  $output['workflow_element_panel']['buttons']['save'] = array(
    '#value' => t('Save'),
    '#type' => 'button',
  );
  $output['workflow_element_panel']['buttons']['cancel'] = array(
    '#value' => t('Cancel'),
    '#type' => 'button',
  );
  $output['workflow_editor'] = array(
    '#prefix' => '<div id="conductor-workflow-editor">',
    '#suffix' => '</div>',
  );
  $activities = conductor_ui_dev_workflow()->getActivities();
  $settings = array();
  $css = '';
  foreach ($activities as $name => $activity) {
    $class_name = 'conductor-ui-activity-' . conductor_ui_css_safe_class($activity->name);
    $settings['activities'][$name] = $activity;
    $activity->css_class = $class_name;
    $output['workflow_editor'][$name] = array(
      '#name' => $activity->name,
      '#class' => $class_name,
      '#theme' => 'conductor_activity',
      '#contextual_links' => array(
        'contextual_example' => array( 'contextual', array('foobars')),
      ),
    );
  }
  drupal_add_css($css, array('type' => 'inline'));
  drupal_add_js(array('conductor_ui' => $settings), array('type' => 'setting'));
  return $output;
}

/**
 * Convert any string into a CSS class.
 *
 * @param $name
 *   The string to be converted into a W3C standards compliant CSS class.
 *
 * @return
 *   The CSS class name.
 */
function conductor_ui_css_safe_class($name) {
  $class_name = preg_replace('/[^a-zA-Z0-9- ]/', '-', strtolower($name));
  $class_name = preg_replace('/\W+/', '-', $class_name);
  $class_name = preg_replace('/\s+/','-', $class_name); 
  return $class_name;
}

/**
 * Add required javascript for the conductor ui.
 */
function conductor_ui_add_js() {
  drupal_add_library('system', 'ui.draggable');
  drupal_add_js(drupal_get_path('module', 'conductor_ui') . '/js/conductor_ui.js');
}

/**
 * Add required css for the conductor ui.
 */
function conductor_ui_add_css() {
  drupal_add_css(drupal_get_path('module', 'conductor_ui') . '/css/conductor_ui.css');
}

function conductor_ui_dev_workflow() {
  $workflow = new ConductorWorkflow;
  $activity = $workflow->newActivity('activity');
  $activity->x = 180;
  $activity->y = 500;
  $activity->name = 'Activity booyeah';
  $activity->inputs = array();
  $activity->outputs = array(
    'Activity 2'
  );
  $activity = $workflow->newActivity('activity');
  $activity->x = 280;
  $activity->y = 200;
  $activity->name = 'Activity 2';
  $activity->inputs = array(
    'Activity 2'
  );
  $activity->outputs = array();
  return $workflow;
}
