<?php

/**
 * @file conductor_ui.module
 *   Provides the admin interface for Conductor.
 */

/**
 * Implements hook_menu().
 *
 * Note most of the Conductor UI is provided by a ctools export_ui plugin.
 * The basic data is defined inplugins/export_ui/conductor_ui.inc.  The class
 * providing the functionality is in plugins/export_ui/conductor_ui.class.inc.
 */
function conductor_ui_menu() {
  $items = array();
  $items['conductor_ui/activity-config/%/%/%ctools_js'] = array(
    'title' => 'Activity',
    'page callback' => 'conductor_ui_activity_form',
    'cancel callback' => 'ctools_ajax_sample_wizard_cancel',
    'page arguments' => array(2, 3, 4),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['admin/structure/conductor/settings'] = array(
    'title' => 'Conductor Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('conductor_ui_admin_settings_form'),
    'access arguments' => array('administer conductor workflows'),
    'file' => 'conductor_ui.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

/**
 * Implements hook_theme();
 */
function conductor_ui_theme() {
  return array(
    'conductor_activity' => array(
      'variables' => array(
        'name' => '',
        'title' => '',
        'class' => '',
        'drop_links' => '',
      ),
      'path' => drupal_get_path('module', 'conductor_ui') . '/theme',
      'template' => 'conductor-activity'
    ),
  );
}


/**
 * Implements hook_library().
 */
function conductor_ui_library() {
  $libraries['jsplumb'] = array(
    'title' => 'jsPlumb',
    'website' => 'http://code.google.com/p/jsplumb/1.3.2/',
    'version' => '1.2.3',
    'js' => array(
      drupal_get_path('module', 'conductor_ui') . '/js/jquery.jsPlumb-1.3.3-all-min.js' => array(),
    ),
    'dependencies' => array(
      array('system', 'jquery'),
      array('system', 'ui'),
      array('system', 'ui.draggable'),
      array('system', 'ui.droppable'),
    ),
  );
  return $libraries;
}

/**
 * Implements hook_ctools_plugin_directory().
 *
 * @param string $owner
 *   The system name of the module owning the plugin type for which a base
 *   directory location is being requested.
 * @param string $plugin_type
 *   The name of the plugin type for which a base directory is being requested.
 * @return string
 *   The path where CTools' plugin system should search for plugin files,
 *   relative to your module's root. Omit leading and trailing slashes.
 */
function conductor_ui_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'export_ui') {
    return "plugins/$plugin_type";
  }
}

/**
 * Implements hook_conductor_activity_process
 * TODO: Test this!
 */
function conductor_ui_conductor_activity_process(&$plugin) {
  $plugin += array(
    'conductor_ui_template' => 'conductor_activity',
  );
}

/**
 * TODO: get this working and get rid of the hideous default modal.
 */
function conductor_ui_add_ctools_modal_style() {
  // Create our own javascript that will be used to theme a modal.
  $sample_style = array(
    'conductor-ui-style' => array(
      'modalSize' => array(
        'type' => 'fixed',
        'width' => 500,
        'height' => 300,
        'addWidth' => 20,
        'addHeight' => 15,
      ),
      'modalOptions' => array(
        'opacity' => .5,
        'background-color' => '#000',
      ),
      'animation' => 'fadeIn',
      'modalTheme' => 'CToolsSampleModal',
      'throbber' => theme('image', array('path' => ctools_image_path('ajax-loader.gif', 'ctools_ajax_sample'), 'alt' => t('Loading...'), 'title' => t('Loading'))),
    ),
  );
  drupal_add_js($sample_style, 'setting');
}

/**
 * The form callback used to load the activity configuration forms.
 */
function conductor_ui_activity_form($workflow_uri_name, $activity_uri_name, $js = NULL) {

  //dpm(func_get_args());
  // We use the ctools wizard here because of its magic ajax and because we
  // expect to grow into it.
  ctools_include('wizard');
  $workflow_name = strtr($workflow_uri_name, array('-' => '_'));
  $activity_name = strtr($activity_uri_name, array('-' => '_'));
  // Load a workflow.
  $form = FALSE;
  if ($workflow = conductor_get_workflow($workflow_name)) {
    if ($activity = $workflow->getActivity($activity_name)) {
      $form = array();
      $form['#workflow'] = $workflow;
      $form['#activity'] = $activity;
      $form = $activity->configureForm();
    }
  }
  // TODO: Clean this all up.  Alot.
  if ($js) {
    ctools_include('modal');
    ctools_include('ajax');
  }

  $form_info = array(
    'path' => 'conductor_ui/activity-config/' . $workflow_uri_name . '/' . $activity_uri_name . '/no-js',
    'show trail' => FALSE,
    'show back' => FALSE,
    'show cancel' => TRUE,
    'show return' => FALSE,
    'order' => array(
      'start' => t('Funktytown'),
    ),
   // here we map a step to a form id.
    'forms' => array(
      // e.g. this for the step at wombat/create
      'start' => array(
        'form id' => 'conductor_ui_activity_get_form'
      ),
    ),
  );

  $form_state = array(
    'ajax' => $js,
    // Put our object and ID into the form state cache so we can easily find
    // it.
    'object_id' => 'new',
    'activity' => &$activity,
    'workflow' => &$workflow,
  );

  $step = 'start';
  $form = ctools_wizard_multistep_form($form_info, $step, $form_state);


  $output = drupal_render($form);
  // If $output is FALSE, there was no actual form.
  if ($js) {
    // If javascript is active, we have to use a render array.
    $commands = array();
    if ($output === FALSE || !empty($form_state['complete'])) {
      // Dismiss the modal.
      $commands[] = ctools_modal_command_dismiss();
    }
    else if (!empty($form_state['cancel'])) {
      // If cancelling, return to the activity.
      $commands[] = ctools_modal_command_dismiss();
    }
    else {
      $commands = ctools_modal_form_render($form_state, $output);
    }
    print ajax_render($commands);
    exit;
  }
  else {
    if ($output === FALSE || !empty($form_state['complete'])) {
      return $animal;
    }
    else if (!empty($form_state['cancel'])) {
      drupal_goto('ctools_ajax_sample');
    }
    else {
      return $output;
    }
  }
}

function conductor_ui_activity_get_form($form, &$form_state) {
  $activity = $form_state['activity'];
  $form = $activity->configureForm($form);
  return $form;
}

function conductor_ui_activity_get_form_validate($form, &$form_state) {
}

function conductor_ui_activity_get_form_submit($form, &$form_state) {
}

/**
 * Convert any string into a CSS class.
 *
 * @param $name
 *   The string to be converted into a W3C standards compliant CSS class.
 *
 * @return
 *   The CSS class name.
 */
function conductor_ui_css_safe_class($name) {
  $class_name = preg_replace('/[^a-zA-Z0-9- ]/', '-', strtolower($name));
  $class_name = preg_replace('/\W+/', '-', $class_name);
  $class_name = preg_replace('/\s+/','-', $class_name); 
  return $class_name;
}

/**
 * Add required javascript for the conductor ui.
 */
function conductor_ui_add_js() {

  // Added for use of ctools modals
  drupal_add_js('misc/ajax.js');
  drupal_add_library('system', 'ui.draggable');

  // Include jsPlumb for drawing our lines
  drupal_add_library('conductor_ui', 'jsplumb');

  // Include the CTools tools that we need.
  drupal_add_js('misc/ajax.js');
  ctools_include('ajax');
  ctools_include('modal');
  ctools_modal_add_js();

  // TODO: Our API allows modules to specify their own js for their own
  // activities.  Auto include it here.

  drupal_add_js(drupal_get_path('module', 'conductor_ui') . '/js/conductor_ui.js');
}

/**
 * Add required css for the conductor ui.
 */
function conductor_ui_add_css() {
  // The views styling for ctools buttons is nice, lets steal it.
  drupal_add_css(drupal_get_path('module', 'views') . '/css/views-admin.ctools.css');
  drupal_add_css(drupal_get_path('module', 'conductor_ui') . '/css/conductor_ui.css');
}

/**
 * Implements hook_default_conductor_default_workflows().
 */
function conductor_ui_default_conductor_workflows() {
  $workflows = array();
  $workflow = new ConductorWorkflow;
  $workflow->wid = 'new';
  $workflow->name = 'example';
  $workflow->title = 'Example';
  $workflow->description = 'example';
  $workflow->api_version = '1.0';
  // Add and configure workflow activities.
  $activity = $workflow->newActivity('start');
  $activity->x = 280;
  $activity->y = 200;
  $activity->name = 'start';
  $activity->title = 'Start';
  $activity->outputs = array(
    'activity_2',
    'activity_3'
  );
  $activity->inputs = array();
  $activity = $workflow->newActivity('activity');
  $activity->x = 180;
  $activity->y = 100;
  $activity->name = 'activity_2';
  $activity->title = 'Activity 2';
  $activity->inputs = array(
    'start',
  );
  $activity->outputs = array(
    'end'
  );
  $activity = $workflow->newActivity('activity');
  $activity->x = 180;
  $activity->y = 100;
  $activity->name = 'activity_3';
  $activity->title = 'Activity 3';
  $activity->inputs = array(
    'start',
  );
  $activity->outputs = array(
    'end'
  );
  $activity = $workflow->newActivity('end');
  $activity->x = 380;
  $activity->y = 200;
  $activity->name = 'end';
  $activity->title = 'End';
  $activity->inputs = array(
    'activity_2',
    'activity_3'
  );
  $activity->outputs = array();
  $workflows[$workflow->name] = $workflow;
  return $workflows;
}

function conductor_ui_ctools_export_ui_form(&$form_state, &$form) {
  


}
function conductor_ui_ctools_export_ui_form_validate(&$form_state, &$form) {
}
function conductor_ui_ctools_export_ui_form_submit(&$form_state, &$form) {
}

/**
 * Specialized cache function to add a flag to our workflow, include an appropriate
 * include, and cache more easily.
 */
function conductor_ui_cache_set(&$workflow) {
  if (!empty($workflow->locked)) {
    drupal_set_message(t('Changes cannot be made to a locked workflow.'), 'error');
    return;
  }
  ctools_include('object-cache');
  $workflow->changed = TRUE; // let any future object know that this workflow has changed.

  // If there is any state information make sure it is not cached.
  unset($workflow->state);

  /*
   TODO: This is probably a good idea, we should avoid saving the handler code in the cache wherever we can.
   we should consider reorganizing the handlers the way views does where the activity_info is the root and
   the handler is an element in that array rather than the other way around.
  // Unset handlers; we don't want to write these into the cache
  unset($workflow->display_handler);
  unset($workflow->default_display);
  $workflow->query = NULL;
  foreach (array_keys($workflow->display) as $id) {
    unset($workflow->display[$id]->handler);
    unset($workflow->display[$id]->default_display);
  }
  */
  ctools_object_cache_set('workflow', $workflow->name, $workflow);
}

/**
 * Set breadcrumbs for admin pages in the Conductor UI
 *
 * @param $sub_path
 *   An array of additional breadcrumb entries to be added to the end of the base path.
 */
function conductor_ui_set_breadcrumb($sub_path = NULL) {
  $breadcrumb = array(
    l(t('Home'), NULL),
    l(t(' Administration'), 'admin'),
    l(t('Structure'), 'admin/structure'),
    l(t('Conductor Workflows'), 'admin/structure/conductor/list'),
  );
  if (!is_null($sub_path)) {
    $breadcrumb = array_merge($breadcrumb, $sub_path);
  }
  drupal_set_breadcrumb($breadcrumb);
}

/**
 * Implements hook_ctools_plugin_api().
 */
function conductor_ui_ctools_plugin_api($owner, $api) {
  // TODO: $api should be workflow, not conductor but that messes with features file naming.
  if ($owner == 'conductor' && $api == 'conductor') {
    return array('version' => 1.0);
  }
}
